#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Start debugpy with your Django application
# python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8001 &
python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8001 &

# Wait for debugpy to start
sleep 5

python manage.py migrate

# python manage.py import_geojson ${DJANGO_ISRAEL_MAP_JSON}
python manage.py import_geojson /app/helpme/static/maps/stanford-ch107xc0728-geojson.json

exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
