#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Start debugpy with your Django application
# python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000 &
python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000

# Wait for debugpy to start
sleep 5

python manage.py migrate
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
