version: '3'

volumes:
  helpme_local_postgres_data: {}
  helpme_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: helpme_local_django
    container_name: helpme_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8001:8001'
      - '5678:5678'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: helpme_production_postgres
    container_name: helpme_local_postgres
    volumes:
      - helpme_local_postgres_data:/var/lib/postgresql/data
      - helpme_local_postgres_data_backups:/backups
      - ./compose/local/postgres:/docker-entrypoint-initdb.d/
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  docs:
    image: helpme_local_docs
    container_name: helpme_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./helpme:/app/helpme:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: helpme_local_mailpit
    ports:
      - '8025:8025'

  redis:
    image: redis:6
    container_name: helpme_local_redis

  celeryworker:
    <<: *django
    image: helpme_local_celeryworker
    container_name: helpme_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: helpme_local_celerybeat
    container_name: helpme_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: helpme_local_flower
    container_name: helpme_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: helpme_local_node
    container_name: helpme_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    restart: always
    depends_on:
      - django
