# Generated by Django 4.2.6 on 2023-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("volunteer", "Volunteer"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
