# Generated by Django 4.2.6 on 2023-10-16 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_contact_number_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
